version: '3.9'

services:
  postgres:
    build:
      context: docker
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
    environment:
      # These will have to be fixed when going live
      - POSTGRES_PASSWORD=brutus
      - POSTGRES_USER=brutus_rw
      - POSTGRES_DB=brutus
  astro:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000